### ISSUE TITLE
Cambios en  algunos textos de la documentación

### ISSUE THREAD

**Issue by jairoufps** [RafaelAybar/qa-empleo#13]
Creo que hay algunos textos que podrían mejorarse en la documentación
por ejemplo

 **5. Espectativas salariales**

**Ubicación del cliente respecto a tu casa**

En las tablas en la sección de tiempo podría asignarse un nombre con algo mas de  contexto a la  variable
_30 min < x >= 60 min_

y en las otras secciones donde se use x igual, esto podría ayudar mas adelante a entender mas fácil el uso del script

y si no hay problema yo podría ayudar en esta parte.

**Comment by RafaelAybar** [comment]
Buenas, ¡encantado de que colabores!
