### ISSUE TITLE
Crear un paquete de Python para distribuir la aplicación (wheel)

### ISSUE THREAD

**Issue by cmaureir** [RafaelAybar/qa-empleo#7]
Guía oficial para poder hacer packaging - https://packaging.python.org/

El proceso puede parecer bastante complicado, pero existen herramientas que ayudan a hacer más facil como [poetry](https://python-poetry.org/), de todas formas lo más sencillo para realizar un 'wheel' es:
* Crear un archivo setup.py con la información del proyecto,
* ejecutar `python setup.py bdist_wheel`
https://packaging.python.org/tutorials/packaging-projects/

Existen muchas combinaciones para hacer esto, algunas personas usan `setup.cfg`, otras se mueven a cosas más nuevas como `pyproject.toml`, pero para una primera versión se podría hacer un setup.py simple.

Una vez con el wheel, el paquete se puede publicar en pypi.org

**Comment by ibLeDy** [comment]
Buenas, me gustaría trabajar en este issue.

**Comment by RafaelAybar** [comment]
Hola, ¡será un placer colaborar contigo!

**Comment by ibLeDy** [comment]
Buenas, no tengo demasiada experiencia con packaging, pero creo que habría que modificar un poco el script para poder usarlo, ya que no tiene un entrypoint, es decir, una función que sería la que llame el comando que ejecutaría el script. 

Habría que crear una función (`main()`, por ejemplo), que albergara `paramsList` y también el resto de líneas (de la 23 a la 34), con lo que sería posible indicarle a setuptools que instale el comando `qa-empleo` que es el que se encarga de usar lo anteriormente citado.

Todo esto es en base a el método que usa [`console_scripts`](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) como entrypoint.

**Comment by ibLeDy** [comment]
Siento la inactividad, prepararé una PR para que puedan ver los cambios directamente.
