### ISSUE TITLE
Elección de versionado

### ISSUE THREAD

**Issue by RafaelAybar** [RafaelAybar/qa-empleo#9]
No tengo claro si hay que versionar la app,  para dockerizarla se genera el tag lastest, y no hace falta nada más, pero si se quiere meter como paquete de pip, habría que usar SemVer y establecer un proceso de release.

**Comment by Frans06** [comment]
Asignamela a mi te ayudo.

**Comment by RafaelAybar** [comment]
> Asignamela a mi te ayudo.

¿Es necesario asignarlo para que cuente?

**Comment by Frans06** [comment]
No estoy seguro, pero es el procedimiento que se esta siguiendo.

**Comment by Frans06** [comment]
Creo que la mejor forma de lograr lo que quierer es usar https://github.com/takluyver/flit. La dockerizacion esta perfecto pero si quieres mantener el tag se necesita tener el container en un repositorio.  Que opinas?

**Comment by RafaelAybar** [comment]
Pues la verdad es que no lo tengo claro, CREO, que salvo Flask no se necesitarían dependencias externas, no sé si hay que añadir un fichero ``VERSION` u hace falta implementar algo más avanzado. Si es fichero version, podría intentar configurar github actions para hacer los pasos del versionado automáticamente.

**Comment by Frans06** [comment]
el punto de flit es ayudar a que puedas publicar en pypi (pip), repositorios como FastAPI lo usan, y no es que te agregue ina dependencia externa solo lo hace para poder empaquetar el codigo y nada mas. NO se intalara en el momento de empaquetar el codigo.

**Comment by RafaelAybar** [comment]
Perfecto entonces.

**Comment by ibLeDy** [comment]
Buenas, `flit` está muy bien, pero para proyectos sencillos como este creo que sería complicarse un poco, ya que para empaquetar y subir una nueva versión sólo hay que seguir 3 pasos, que son los siguientes:

1. actualizar el argumento `version="X.X.X"` en el archivo `setup.py`
2. ejecutar el comando de empaquetamiento: `python3 setup.py sdist bdist_wheel`
3. subir paquete a PyPi: `twine upload dist/*`

**Comment by Frans06** [comment]
@RafaelAybar  si es cierto que podria ser algo mas simple. Pero  creo que la opcion de crecer el repo esta presente. Entonces seria bueno que se utilizara flit.
Hare el PR. Creo que deberias ser tu el que tenga el control de paquete. Para eso necesitas registrarte en:
https://pypi.org/account/register/
luego de eso hacer 
```bash 
flit publish
```
Tambien puedes llenar mas de tu informacion en el archivo pyproject.toml

**Comment by Frans06** [comment]
#11 @RafaelAybar
